import React from 'react';

const SIDENAV_LINKS = [
    {
        TITLE: 'Getting Started',
        LINKS: [
            { URL: '/getting-started/introduction', TEXTNODE: 'Introduction' },
            { URL: '/getting-started/getting-started-with-j2store', TEXTNODE: 'Getting started with J2Store' },
            { URL: '/getting-started/technical-requirements', TEXTNODE: 'Technical Requirements' },
            { URL: '/getting-started/installation', TEXTNODE: 'Installation' },
            { URL: '/getting-started/update', TEXTNODE: 'Update' },
            { URL: '/getting-started/migrating-from-2x-to-3x', TEXTNODE: 'Migrating from 2.x to 3.x' },
            { URL: '/getting-started/upgrade-free-version-to-pro-version', TEXTNODE: 'Upgrade Free version to Pro version' },
        ],
        BUTTON_LINK: '/getting-started/introduction',
    },
    {
        TITLE: 'Set up',
        LINKS: [
            { URL: '/set-up/content-plugin-settings', TEXTNODE: 'Content plugin settings' },
            { URL: '/set-up/configuration', TEXTNODE: 'Configuration' },
            { URL: '/set-up/currency', TEXTNODE: 'Currency' },
            { URL: '/set-up/custom-fields', TEXTNODE: 'Custom Fields' },
            { URL: '/set-up/setup-multi-currencysetup-multi-currency', TEXTNODE: 'Setup Multi currency' },
        ],
        BUTTON_LINK: '/set-up/content-plugin-settings',
    },
    {
        TITLE: 'Quick Start',
        LINKS: [
            { URL: '/quick-start/quick-start-guide', TEXTNODE: 'Quick Start Guide' },
        ],
        BUTTON_LINK: '/quick-start/quick-start-guide',
    },
    {
        TITLE: 'Frequently Asked Questions',
        LINKS: [
            { URL: '/frequently-asked-questions/products-are-not-aligned-properly-on-list-view', TEXTNODE: 'Products are not aligned properly on list view' },
            { URL: '/frequently-asked-questions/to-show-the-base-price-instead-of-price-range-in-flexivariable-products', TEXTNODE: 'To show the base price instead of price range in flexivariable products' },
            { URL: '/frequently-asked-questions/sca-support-for-payment-plugins', TEXTNODE: 'SCA support for payment plugins' },
            { URL: '/frequently-asked-questions/where-do-i-add-the-css-on-my-site', TEXTNODE: 'Where do I add the CSS on my site' },
            { URL: '/frequently-asked-questions/not-able-to-save-the-settings-in-any-app', TEXTNODE: 'Not able to save the settings in any app' },
            { URL: '/frequently-asked-questions/difference-between-product-types', TEXTNODE: 'Difference between product types' },
            { URL: '/frequently-asked-questions/commonly-found-issues', TEXTNODE: 'Commonly found issues' },
            { URL: '/frequently-asked-questions/frequently-asked-questions', TEXTNODE: 'Frequently Asked Questions' },
            { URL: '/frequently-asked-questions/quantity-restriction', TEXTNODE: 'Quantity restriction' },

        ],
        BUTTON_LINK: '/frequently-asked-questions/products-are-not-aligned-properly-on-list-view',
    },
    {
        TITLE: 'Troubleshooting Guide',
        LINKS: [
            { URL: '/troubleshooting-guide/product-not-visible-on-store-front', TEXTNODE: 'Product not visible on store front' },
            { URL: '/troubleshooting-guide/cart-not-working', TEXTNODE: 'Cart not working' },
            { URL: '/troubleshooting-guide/troubleshoot-cart-related-issues', TEXTNODE: 'Troubleshoot cart related issues' },
            { URL: '/troubleshooting-guide/moving-the-description', TEXTNODE: 'Moving the description' },
            { URL: '/troubleshooting-guide/troubleshooting-checkout-issues', TEXTNODE: 'Troubleshooting Checkout issues' },
            { URL: '/troubleshooting-guide/troubleshooting-common-issues', TEXTNODE: 'Troubleshooting Common Issues' },
            { URL: '/troubleshooting-guide/how-to-disable-shipping-address-step-and-payment-methods-in-checkout', TEXTNODE: 'HOW TO Disable Shipping Address step and Payment Methods in Checkout' },
            { URL: '/troubleshooting-guide/troubleshoot-email-issues', TEXTNODE: 'Troubleshoot Email Issues' },
            { URL: '/troubleshooting-guide/joomla-article-error-decoding-json-data', TEXTNODE: 'Joomla article error decoding json data' },
            { URL: '/troubleshooting-guide/troubleshooting-paypal-related-issues', TEXTNODE: 'Troubleshooting Paypal Related Issues' },
            { URL: '/troubleshooting-guide/troubleshoot-product-display-module-issues', TEXTNODE: 'Troubleshoot product display module issues' },
            { URL: '/troubleshooting-guide/howto-create-a-custom-thank-you-message', TEXTNODE: 'HOWTO create a custom thank you message' },
            { URL: '/troubleshooting-guide/troubleshooting-shipping-methods', TEXTNODE: 'Troubleshooting shipping methods' },
            { URL: '/troubleshooting-guide/troubleshooting-tax-issues', TEXTNODE: 'Troubleshooting Tax Issues' },
            { URL: '/troubleshooting-guide/troubleshoot-translate-related-issues', TEXTNODE: 'Troubleshoot translate related issues' },
        ],
        BUTTON_LINK: '/troubleshooting-guide/product-not-visible-on-store-front',
    },
    {
        TITLE: 'Catalog',
        LINKS: [
            {URL: '/catalog/translating-filters-to-your-language', TEXTNODE:'Translating filters to your language' }, 
            {URL: '/catalog/where-can-i-find-my-sub-template', TEXTNODE:'Where can i find my sub-template?' }, 
            {URL: '/catalog/how-to-create-options-and-add-them-to-your-products', TEXTNODE:'How to create options and add them to your products' }, 
            {URL: '/catalog/setting-up-tax-for-your-products', TEXTNODE:'Setting up tax for your products' }, 
            {URL: '/catalog/simple-product', TEXTNODE:'Simple Product' }, 
            {URL: '/catalog/configurable-product', TEXTNODE:'Configurable Product' }, 
            {URL: '/catalog/variable-product', TEXTNODE:'Variable Product' }, 
            {URL: '/catalog/flexible-variable', TEXTNODE:'Flexible Variable' }, 
            {URL: '/catalog/downloadable-product', TEXTNODE:'Downloadable Product' }, 
            {URL: '/catalog/assigning-a-product-to-multiple-categories', TEXTNODE:'Assigning a product to multiple categories' }, 
            {URL: '/catalog/options', TEXTNODE:'Options' }, 
            {URL: '/catalog/import-product-options', TEXTNODE:'Import product options' }, 
            {URL: '/catalog/product-filters', TEXTNODE:'Product Filters' }, 
            {URL: '/catalog/manufacturers', TEXTNODE:'Manufacturers' }, 
            {URL: '/catalog/vendors', TEXTNODE:'Vendors' }, 
            {URL: '/catalog/short-codes', TEXTNODE:'Short codes' }, 
            {URL: '/catalog/product-description', TEXTNODE:'Product Description' }, 
            {URL: '/catalog/advanced-pricing', TEXTNODE:'Advanced Pricing' }, 
            {URL: '/catalog/adding-specifications-to-your-products', TEXTNODE:'Adding Specifications to your products' }, 
            {URL: '/catalog/adding-related-products', TEXTNODE:'Adding related products' }, 
            {URL: '/catalog/ordering-products-on-your-storefront', TEXTNODE:'Ordering products on your storefront' }, 
        ],
        BUTTON_LINK: '/catalog/translating-filters-to-your-language',
    },
    {
        TITLE: 'Subscriptions & Memberships',
        LINKS: [
            {URL: '/subscriptions-and-memberships/introduction-to-subscriptions-and-memberships-in-j2store', TEXTNODE:'Introduction to Subscriptions and Memberships in J2Store' },
            {URL: '/subscriptions-and-memberships/quickstart', TEXTNODE:'Quickstart' },
            {URL: '/subscriptions-and-memberships/requirements-and-installation', TEXTNODE:'Requirements and Installation' },
            {URL: '/subscriptions-and-memberships/basic-settings', TEXTNODE:'Basic settings' },
            {URL: '/subscriptions-and-memberships/creating-subscriptions-based-products', TEXTNODE:'Creating subscriptions based products' },
            {URL: '/subscriptions-and-memberships/simple-subscription-product', TEXTNODE:'Simple subscription product' },
            {URL: '/subscriptions-and-memberships/paypal-reference-transactions-for-subscriptions', TEXTNODE:'PayPal Reference Transactions for Subscriptions' },
            {URL: '/subscriptions-and-memberships/usecases', TEXTNODE:'Usecases' },
            {URL: '/subscriptions-and-memberships/customizing-the-subscription-mail-templates', TEXTNODE:'Customizing the Subscription  Mail Templates' },
            {URL: '/subscriptions-and-memberships/frequently-asked-questions', TEXTNODE:'Frequently Asked Questions' },
        ],
        BUTTON_LINK: '/subscriptions-and-memberships/introduction-to-subscriptions-and-memberships-in-j2store',
    },
    {
        TITLE: 'Partial payments',
        LINKS: [
            {URL: '/partial-payments/partial-payments', TEXTNODE:'Partial payments' },
            {URL: '/partial-payments/basic-settings', TEXTNODE:'Basic Settings' },
            {URL: '/partial-payments/setting-up-plans-for-partial-payments', TEXTNODE:'Setting up plans for partial payments' },
            {URL: '/partial-payments/instances', TEXTNODE:'Instances' },
            {URL: '/partial-payments/use-cases', TEXTNODE:'Use cases' },
        ],
        BUTTON_LINK: '/partial-payments/partial-payments',
    },
    {
        TITLE: 'Booking and Reservations',
        LINKS: [
            {URL: '/booking-and-reservations/limitations-of-the-booking-product-type', TEXTNODE:'Limitations of the booking product type' },
            {URL: '/booking-and-reservations/how-to-restrict-multiple-booking-for-a-productperson-based-restriction', TEXTNODE:'How to restrict multiple booking for a product(person based restriction)' },
            {URL: '/booking-and-reservations/booking-and-reservations', TEXTNODE:'Booking and Reservations' },
            {URL: '/booking-and-reservations/requirements-and-installation', TEXTNODE:'Requirements and Installation' },
            {URL: '/booking-and-reservations/basic-settings-and-booking-management', TEXTNODE:'Basic settings and booking management' },
            {URL: '/booking-and-reservations/creating-a-bookable-product', TEXTNODE:'Creating a bookable product' },
            {URL: '/booking-and-reservations/use-cases', TEXTNODE:'Use cases' },
        ],
        BUTTON_LINK: '/booking-and-reservations/limitations-of-the-booking-product-type',
    },
    {
        TITLE: 'Layout',
        LINKS: [
            {URL: '/layout/product-layout', TEXTNODE:'Product Layout' },
            {URL: '/layout/product-tag-layout', TEXTNODE:'Product Tag Layout' },
            {URL: '/layout/usecases', TEXTNODE:'Usecases' },
            {URL: '/layout/category-tree-for-displaying-filters', TEXTNODE:'Category Tree for displaying filters' },
            {URL: '/layout/special-module-positions', TEXTNODE:'Special Module Positions' },
        ],
        BUTTON_LINK: '/layout/product-layout',
    },
    {
        TITLE: 'Localisation',
        LINKS: [
            { URL: '/localisation/localisation', TEXTNODE: 'Localisation' },
        ],
        BUTTON_LINK: '/localisation/localisation',
    },
    {
        TITLE: 'Translation',
        LINKS: [
            { URL:'/translation/translate-j2store-in-your-language', TEXTNODE: 'Translate J2Store in your Language'},
            { URL:'/translation/setting-up-the-store-in-your-language', TEXTNODE: 'Setting up the store in your language'},
            { URL:'/translation/how-to-write-language-override-for-plugin-in-multilingual-site', TEXTNODE: 'How to write language override for plugin in multilingual site'},
            { URL:'/translation/language-overrides-in-joomla-with-examples-using-j2store', TEXTNODE: 'Language overrides in Joomla (with examples using J2Store)'},
            { URL:'/translation/translating-product-options', TEXTNODE: 'Translating product options'}            
        ],
        BUTTON_LINK: '/translation/translate-j2store-in-your-language',
    },
    {
        TITLE: 'Design',
        LINKS: [
            { URL: '/design/email-templates', TEXTNODE: 'Email Templates' },
            { URL: '/design/invoice-template-pro-feature', TEXTNODE: 'Invoice Template (PRO Feature)' },
        ],
        BUTTON_LINK: '/design/email-templates',
    },
    {
        TITLE: 'Tax Configuration',
        LINKS: [
            { URL:'/tax-configuration/recommended-tax-configuration-for-us-stores',TEXTNODE:'Recommended Tax configuration for US Stores'},
            { URL:'/tax-configuration/recommended-tax-configuration-for-canadian-stores',TEXTNODE:'Recommended Tax configuration for Canadian Stores'},
            { URL:'/tax-configuration/recommended-tax-configuration-for-eu-stores',TEXTNODE:'Recommended Tax configuration for EU Stores'},
            { URL:'/tax-configuration/setting-up-european-vat-rules-for-selling-physical-goods-with-j2store',TEXTNODE:'Setting up European VAT rules for selling physical goods with J2Store'},
            { URL:'/tax-configuration/a-simplified-guide-for-new-eu-vat-rules-2015-for-digital-goods-and-setting-them-up-in-j2store',TEXTNODE:'A simplified guide for New EU VAT rules 2015 for digital goods and setting them up in J2Store'},
        ],
        BUTTON_LINK: '/tax-configuration/recommended-tax-configuration-for-us-stores',
    },
    {
        TITLE: 'Easy checkout',
        LINKS: [
            { URL: '/easy-checkout/easy-checkout', TEXTNODE: 'Easy checkout' },
            { URL: '/easy-checkout/troubleshooting-easy-checkout', TEXTNODE: 'Troubleshooting Easy checkout' }
        ],
        BUTTON_LINK: '/easy-checkout/easy-checkout',
    },
    {
        TITLE: 'Shipping methods',
        LINKS: [
            { URL: '/shipping-methods/how-to-set-up-a-local-store-pick-up-shipping-method', TEXTNODE: 'Australia Post Shipping Plugin' },
            { URL: '/shipping-methods/australia-post-shipping-plugin', TEXTNODE: 'How to set up a local store pick up shipping method' },
            { URL: '/shipping-methods/bring-shipping-plugin', TEXTNODE: 'Bring Shipping Plugin' },
            { URL: '/shipping-methods/canadapost-shipping-plugin', TEXTNODE: 'Canadapost Shipping Plugin' },
            { URL: '/shipping-methods/dhl-shipping-plugin', TEXTNODE: 'DHL Shipping Plugin' },
            { URL: '/shipping-methods/fedex-shipping-plugin', TEXTNODE: 'FedEx Shipping Plugin' },
            { URL: '/shipping-methods/purolator', TEXTNODE: 'Purolator' },
            { URL: '/shipping-methods/postal-code-shipping-plugin', TEXTNODE: 'Postal Code Shipping Plugin' },
            { URL: '/shipping-methods/royal-mail-shipping', TEXTNODE: 'Royal Mail Shipping' },
            { URL: '/shipping-methods/standard-shipping-methods', TEXTNODE: 'Standard Shipping Methods' },
            { URL: '/shipping-methods/table-rate-shipping', TEXTNODE: 'Table Rate Shipping' },
            { URL: '/shipping-methods/ups-shipping-plugin', TEXTNODE: 'UPS Shipping Plugin' },
            { URL: '/shipping-methods/united-states-postal-service-shipping-plugin', TEXTNODE: 'United States Postal Service Shipping Plugin' },
            { URL: '/shipping-methods/usps-advanced', TEXTNODE: 'USPS Advanced' },
        ],
        BUTTON_LINK: '/shipping-methods/how-to-set-up-a-local-store-pick-up-shipping-method',
    },
    {
        TITLE: 'Sales',
        LINKS: [
            { URL: '/sales/how-to-create-coupons-for-free-shipping', TEXTNODE: 'How to create coupons for free shipping?'},
            { URL: '/sales/coupons', TEXTNODE: 'Coupons'},
            { URL: '/sales/promotions', TEXTNODE: 'Promotions'},
            { URL: '/sales/vouchers', TEXTNODE: 'Vouchers'},
            { URL: '/sales/customers', TEXTNODE: 'Customers'},
            { URL: '/sales/orders', TEXTNODE: 'Orders'},
        ],
        BUTTON_LINK: '/sales/how-to-create-coupons-for-free-shipping',
    },
    {
        TITLE: 'Reporting',
        LINKS: [
            { URL: '/reporting/report-sales', TEXTNODE: 'Report Sales' },
        ],
        BUTTON_LINK: '/reporting/report-sales',
    },
    {
        TITLE: 'Modules',
        LINKS: [
            { URL: '/modules/product-search-module', TEXTNODE:'Product Search Module' },
            { URL: '/modules/j2store-detailed-cart', TEXTNODE:'J2Store Detailed Cart' },
            { URL: '/modules/product-categories-module', TEXTNODE:'Product categories module' },
            { URL: '/modules/product-display-module', TEXTNODE:'Product display module' }
        ],
        BUTTON_LINK: '/modules/product-search-module',
    },
    {
        TITLE: 'Payment Methods',
        LINKS: [
            { URL: '/payment-methods/stripe' , TEXTNODE: 'Stripe' },
            { URL: '/payment-methods/google-customer-review-app' , TEXTNODE: 'Google Customer review app' },
            { URL: '/payment-methods/mollie-payment-plugin' , TEXTNODE: 'Mollie payment plugin' },
            { URL: '/payment-methods/braintree-payment-plugin' , TEXTNODE: 'Braintree Payment plugin' },
            { URL: '/payment-methods/gestpay' , TEXTNODE: 'GestPay' },
            { URL: '/payment-methods/authorizenet-plugin' , TEXTNODE: 'Authorize.Net Plugin' },
            { URL: '/payment-methods/dibs-payment-plugin' , TEXTNODE: 'DIBS Payment Plugin' },
            { URL: '/payment-methods/bank-transfer' , TEXTNODE: 'Bank Transfer' },
            { URL: '/payment-methods/barclays-epdq-payment-plugin' , TEXTNODE: 'Barclays ePDQ Payment Plugin' },
            { URL: '/payment-methods/cash-on-delivery' , TEXTNODE: 'Cash on Delivery' },
            { URL: '/payment-methods/cardsave-pyament-plugin' , TEXTNODE: 'CardSave Pyament Plugin' },
            { URL: '/payment-methods/ccavenue-payment-plugin' , TEXTNODE: 'CCAvenue Payment Plugin' },
            { URL: '/payment-methods/ceca-payment' , TEXTNODE: 'CECA Payment' },
            { URL: '/payment-methods/checkoutfi' , TEXTNODE: 'Checkout.fi' },
            { URL: '/payment-methods/culqi-payment' , TEXTNODE: 'Culqi Payment' },
            { URL: '/payment-methods/dibs-payment-window-plugin' , TEXTNODE: 'DIBS Payment Window Plugin' },
            { URL: '/payment-methods/direcpay-payment-plugin' , TEXTNODE: 'DirecPay Payment Plugin' },
            { URL: '/payment-methods/ebs-payment-plugin' , TEXTNODE: 'EBS Payment Plugin' },
            { URL: '/payment-methods/ets-payment-plugin' , TEXTNODE: 'ETS Payment Plugin' },
            { URL: '/payment-methods/eway-payment-gateway-for-j2store' , TEXTNODE: 'eWay Payment gateway for J2Store' },
            { URL: '/payment-methods/heartland-payment-plugin' , TEXTNODE: 'Heartland Payment Plugin' },
            { URL: '/payment-methods/icepay-payment-plugin' , TEXTNODE: 'IcePay Payment Plugin' },
            { URL: '/payment-methods/interpay' , TEXTNODE: 'Interpay' },
            { URL: '/payment-methods/mercadopago-payment' , TEXTNODE: 'Mercadopago payment' },
            { URL: '/payment-methods/money-order' , TEXTNODE: 'Money Order' },
            { URL: '/payment-methods/moneris-eselectplus-hosted-paypage' , TEXTNODE: 'Moneris eSelectPlus Hosted Paypage' },
            { URL: '/payment-methods/nochex-payment-plugin' , TEXTNODE: 'Nochex Payment Plugin' },
            { URL: '/payment-methods/nmi-payment-gateway' , TEXTNODE: 'NMI Payment Gateway' },
            { URL: '/payment-methods/ogone-payment-plugin' , TEXTNODE: 'Ogone Payment Plugin' },
            { URL: '/payment-methods/pagseguro-payment-plugin' , TEXTNODE: 'PagSeguro Payment Plugin' },
            { URL: '/payment-methods/paybox-payment-plugin' , TEXTNODE: 'Paybox Payment Plugin' },
            { URL: '/payment-methods/payeezy' , TEXTNODE: 'Payeezy' },
            { URL: '/payment-methods/payfast-payment-plugin' , TEXTNODE: 'Payfast Payment Plugin' },
            { URL: '/payment-methods/payflow-pro-payment-plugin' , TEXTNODE: 'Payflow PRO Payment Plugin' },
            { URL: '/payment-methods/paygate-payment' , TEXTNODE: 'PayGate Payment' },
            { URL: '/payment-methods/paymill-payment-plugin' , TEXTNODE: 'Paymill Payment Plugin' },
            { URL: '/payment-methods/paypal-payment-plugin' , TEXTNODE: 'Paypal Payment Plugin' },
            { URL: '/payment-methods/paypal-sandbox' , TEXTNODE: 'PayPal Sandbox' },
            { URL: '/payment-methods/paypal-advanced-payment-plugin' , TEXTNODE: 'Paypal Advanced Payment Plugin' },
            { URL: '/payment-methods/paypal-express-checkout' , TEXTNODE: 'Paypal Express Checkout' },
            { URL: '/payment-methods/paypal-pro-payment-plugin' , TEXTNODE: 'Paypal PRO Payment Plugin' },
            { URL: '/payment-methods/paypal-plus' , TEXTNODE: 'Paypal Plus' },
            { URL: '/payment-methods/payseal-payment-plugin' , TEXTNODE: 'Payseal Payment Plugin' },
            { URL: '/payment-methods/payson-payment-plugin' , TEXTNODE: 'Payson Payment Plugin' },
            { URL: '/payment-methods/payson-invoice-payment-plugin' , TEXTNODE: 'Payson Invoice Payment Plugin' },
            { URL: '/payment-methods/pay-u-latam' , TEXTNODE: 'Pay U Latam' },
            { URL: '/payment-methods/post-finance' , TEXTNODE: 'Post Finance' },
            { URL: '/payment-methods/razorpay' , TEXTNODE: 'Razorpay' },
            { URL: '/payment-methods/realex-payment-plugin' , TEXTNODE: 'RealEx Payment Plugin' },
            { URL: '/payment-methods/saferpay-payment-plugin' , TEXTNODE: 'Saferpay Payment Plugin' },
            { URL: '/payment-methods/sagepay-payment-plugin' , TEXTNODE: 'Sagepay Payment Plugin' },
            { URL: '/payment-methods/sagepay-direct' , TEXTNODE: 'Sagepay Direct' },
            { URL: '/payment-methods/sagepay-form-payment-plugin' , TEXTNODE: 'Sagepay Form Payment Plugin' },
            { URL: '/payment-methods/secure-trading-plugin' , TEXTNODE: 'Secure Trading Plugin' },
            { URL: '/payment-methods/sermepa-payment-plugin' , TEXTNODE: 'Sermepa Payment Plugin' },
            { URL: '/payment-methods/skrill-payment-plugin' , TEXTNODE: 'Skrill Payment Plugin' },
            { URL: '/payment-methods/sisow-payment-plugin' , TEXTNODE: 'Sisow Payment Plugin' },
            { URL: '/payment-methods/sofort-banking' , TEXTNODE: 'Sofort Banking' },
            { URL: '/payment-methods/squareup-payments' , TEXTNODE: 'Squareup Payments' },
            { URL: '/payment-methods/telecash-payment-plugin' , TEXTNODE: 'Telecash Payment Plugin' },
            { URL: '/payment-methods/tranzila-payment-plugin' , TEXTNODE: 'Tranzila Payment Plugin' },
            { URL: '/payment-methods/virtual-merchant-payment-plugin' , TEXTNODE: 'Virtual Merchant Payment Plugin' },
            { URL: '/payment-methods/voguepay-payment-plugin' , TEXTNODE: 'Voguepay Payment Plugin' },
            { URL: '/payment-methods/wirecard-payment-gateway' , TEXTNODE: 'Wirecard payment gateway' },
            { URL: '/payment-methods/worldpay-payment-plugin' , TEXTNODE: 'WorldPay Payment Plugin' },
            { URL: '/payment-methods/yandex-money-payment-plugin' , TEXTNODE: 'Yandex Money Payment Plugin' },
            { URL: '/payment-methods/2checkout-plugin' , TEXTNODE: '2Checkout Plugin' }

        ],
        BUTTON_LINK: '/payment-methods/stripe',
    },
    {
        TITLE: 'Apps',
        LINKS: [
            { URL: '/apps/tax-utilities', TEXTNODE: 'Tax utilities' },
            { URL: '/apps/email-basket-issues', TEXTNODE: 'Email basket issues' },
            { URL: '/apps/language-based-currency', TEXTNODE: 'Language based currency' },
            { URL: '/apps/how-to-send-download-links-through-email-notifications', TEXTNODE: 'How to send download links through email notifications' },
            { URL: '/apps/additional-fee', TEXTNODE: 'Additional fee' },
            { URL: '/apps/discount-for-payment-methods', TEXTNODE: 'Discount for Payment methods' },
            { URL: '/apps/acymailing-integration-app', TEXTNODE: 'AcyMailing Integration App' },
            { URL: '/apps/additional-terms-and-conditions', TEXTNODE: 'Additional Terms and Conditions' },
            { URL: '/apps/add-to-user-group', TEXTNODE: 'Add to User Group' },
            { URL: '/apps/advanced-notify', TEXTNODE: 'Advanced Notify' },
            { URL: '/apps/advanced-csv-import-export', TEXTNODE: 'Advanced CSV Import / Export' },
            { URL: '/apps/advanced-tax-rate', TEXTNODE: 'Advanced Tax Rate' },
            { URL: '/apps/advanced-variable', TEXTNODE: 'Advanced Variable' },
            { URL: '/apps/amazon-s3', TEXTNODE: 'Amazon S3' },
            { URL: '/apps/ask-question-quote', TEXTNODE: 'Ask question / quote' },
            { URL: '/apps/auto-currency-switch', TEXTNODE: 'Auto Currency Switch' },
            { URL: '/apps/availability-notification', TEXTNODE: 'Availability Notification' },
            { URL: '/apps/bulk-discounts', TEXTNODE: 'Bulk discounts' },
            { URL: '/apps/bundled-products', TEXTNODE: 'Bundled Products' },
            { URL: '/apps/cart-item-limit', TEXTNODE: 'Cart Item Limit' },
            { URL: '/apps/cb-profile-sync', TEXTNODE: 'CB Profile Sync' },
            { URL: '/apps/compare-products', TEXTNODE: 'Compare products' },
            { URL: '/apps/content-custom-fields', TEXTNODE: 'Content Custom Fields' },
            { URL: '/apps/data-validation', TEXTNODE: 'Data Validation' },
            { URL: '/apps/dropbox', TEXTNODE: 'Dropbox' },
            { URL: '/apps/email-basket-plugin', TEXTNODE: 'Email Basket Plugin' },
            { URL: '/apps/enhanced-e-commerce-google-analytics', TEXTNODE: 'Enhanced E-commerce Google Analytics' },
            { URL: '/apps/facebook-conversion-pixel-tracking', TEXTNODE: 'Facebook Conversion Pixel tracking' },
            { URL: '/apps/gdpr-compliance', TEXTNODE: 'GDPR Compliance' },
            { URL: '/apps/geoip-product-rules', TEXTNODE: 'GeoIP Product Rules' },
            { URL: '/apps/gift-cards', TEXTNODE: 'Gift Cards' },
            { URL: '/apps/google-analytics-ecommerce-tracking', TEXTNODE: 'Google Analytics ECommerce Tracking' },
            { URL: '/apps/google-merchant-center-shopping-feed', TEXTNODE: 'Google Merchant Center - Shopping feed' },
            { URL: '/apps/group-products', TEXTNODE: 'Group Products' },
            { URL: '/apps/image-popup', TEXTNODE: 'Image Popup' },
            { URL: '/apps/invoice-prefix-generator', TEXTNODE: 'Invoice Prefix Generator' },
            { URL: '/apps/jcomments', TEXTNODE: 'JComments' },
            { URL: '/apps/mailchimp', TEXTNODE: 'Mailchimp' },
            { URL: '/apps/mijoshop-migration-app-for-j2store', TEXTNODE: 'Mijoshop Migration App for J2Store' },
            { URL: '/apps/nexmo-sms', TEXTNODE: 'Nexmo SMS' },
            { URL: '/apps/open-hours-time-based-restriction', TEXTNODE: 'Open Hours (time based restriction)' },
            { URL: '/apps/pay-later-pay-against-invoice', TEXTNODE: 'Pay Later / Pay against Invoice' },
            { URL: '/apps/pdf-invoices', TEXTNODE: 'PDF Invoices' },
            { URL: '/apps/points-and-rewards', TEXTNODE: 'Points and Rewards' },
            { URL: '/apps/price-suffix-texts', TEXTNODE: 'Price Suffix Texts' },
            { URL: '/apps/quantity-dropdown', TEXTNODE: 'Quantity Dropdown' },
            { URL: '/apps/quickbooks-online', TEXTNODE: 'Quickbooks Online' },
            { URL: '/apps/re-captcha-for-j2store-register', TEXTNODE: 'Re-Captcha for J2Store Register' },
            { URL: '/apps/restrict-shipping', TEXTNODE: 'Restrict shipping' },
            { URL: '/apps/shipstation', TEXTNODE: 'Shipstation' },
            { URL: '/apps/simple-csv-import-and-export', TEXTNODE: 'Simple CSV Import and Export' },
            { URL: '/apps/social-media-share-plugin', TEXTNODE: 'social-media-share-plugin' },
            { URL: '/apps/stampscom', TEXTNODE: 'Stamps.com' },
            { URL: '/apps/tax-exempt', TEXTNODE: 'Tax Exempt' },
            { URL: '/apps/twilio-sms', TEXTNODE: 'Twilio SMS' },
            { URL: '/apps/upload-file-in-checkout', TEXTNODE: 'Upload file in checkout' },
            { URL: '/apps/vm-migration-app-for-j2store', TEXTNODE: 'VM Migration App for J2Store' },
            { URL: '/apps/wishlist', TEXTNODE: 'Wishlist' },
            { URL: '/apps/zoho-crm-integration', TEXTNODE: 'Zoho CRM Integration' },
        ],
        BUTTON_LINK: '/apps/tax-utilities',
    },
    {
        TITLE: 'Integrations',
        LINKS: [
            { URL: '/integrations/sp-page-builder', TEXTNODE: 'SP Page Builder' },
            { URL: '/integrations/dj-catalog2', TEXTNODE: 'DJ Catalog2' },
            { URL: '/integrations/flexicontent', TEXTNODE: 'FLEXIcontent' },
            { URL: '/integrations/jevents', TEXTNODE: 'JEvents' },
            { URL: '/integrations/seblod', TEXTNODE: 'Seblod' },
            { URL: '/integrations/rs-events-pro-for-j2store', TEXTNODE: 'RS Events Pro for J2Store' },
            { URL: '/integrations/sobipro', TEXTNODE: 'SobiPro' },
            { URL: '/integrations/tz-portfolio', TEXTNODE: 'TZ Portfolio' },
            { URL: '/integrations/zoo', TEXTNODE: 'Zoo' },
        ],
        BUTTON_LINK: '/integrations/sp-page-builder',
    },
    {
        TITLE: 'General',
        LINKS: [
            { URL: '/general/how-to-set-cron-job-on-your-server', TEXTNODE: 'How to set cron job on your server?' },
            { URL: '/general/how-to-create-an-ftp-account-and-super-user-account-in-joomla', TEXTNODE: 'How to create an FTP account and super user account in Joomla' },
        ],
        BUTTON_LINK: '/general/how-to-set-cron-job-on-your-server',
    },
    {
        TITLE: 'Developer Guide',
        LINKS: [
            { URL: '/developer-guide/sub-templates', TEXTNODE: 'Sub templates' },
            { URL: '/developer-guide/getting-started/introduction', TEXTNODE: 'Introduction' },
            { URL: '/developer-guide/getting-started/queue-system', TEXTNODE: 'Queue System' },
            { URL: '/developer-guide/plugins/app-for-j2store', TEXTNODE: 'App for J2Store' },
            { URL: '/developer-guide/plugins/creating-an-integration-plugin-for-your-component', TEXTNODE: 'Creating an integration plugin for your component' },
            { URL: '/developer-guide/plugins/payment-plugins', TEXTNODE: 'Payment Plugins' },
            { URL: '/developer-guide/design/templates', TEXTNODE: 'Templates' },
        ],
        BUTTON_LINK: '/developer-guide/sub-templates',
    },
    {
        TITLE: 'Canonical URL plugin',
        LINKS: [
            { URL: '/canonical-url-plugin/canonical-url-plugin', TEXTNODE: 'Canonical URL plugin' },
        ],
        BUTTON_LINK: '/canonical-url-plugin/canonical-url-plugin',
    },
    {
        TITLE: 'Common overrides',
        LINKS: [
            { URL: '/common-overrides/to-add-options-to-downloadable-products', TEXTNODE: 'To add options to downloadable products' },
            { URL: '/common-overrides/moving-additional-image-list-to-the-left-of-the-main-image-in-product-view-page', TEXTNODE: 'Moving additional image list to the left of the main image in product view page' },
            { URL: 'common-overrides/to-display-the-upcebanisbn-on-the-product-page', TEXTNODE: 'To display the UPC/EBAN/ISBN on the product page' },
            { URL: 'common-overrides/to-display-both-the-main-image-and-the-additional-image-in-the-product-view-page', TEXTNODE: 'To display both the main image and the additional image in the product view page' },
        ],
        BUTTON_LINK: '/common-overrides/to-add-options-to-downloadable-products',
    },
];

export default SIDENAV_LINKS;